server {
  listen 80;
  server_name _;

  client_max_body_size 500m;

  location = /api/onlyoffice/callback {
    default_type application/json;
    return 200 '{"error":0}';
  }

  location / {
    proxy_pass http://host.docker.internal:6767;
    proxy_http_version 1.1;
    proxy_buffering off;

    proxy_set_header Host localhost:6767;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto http;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
